export enum CREDIT_CARD_CODES {
  QPCA = "qpca",
  QPCB = "qpcb",
  QPCC = "qpcc",
}

export enum APPLICATION_STEPS {
  CHOOSE_CARD = "CHOOSE_CARD",
  PERSONAL_DETAILS = "PERSONAL_DETAILS",
  FINANCIAL_DETAILS = "FINANCIAL_DETAILS",
  REVIEW_CONFIRM = "REVIEW_CONFIRM",
}
